Repository AY2324S2-CS2103T-W09-1/tp, pull requests merged in 2024-03, with the labels that each got.

#15 Tutorial adding command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.HIGH

#18 Change website title and GitHub link
  docs/_config.yml
Labels: documentation

#19 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#36 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium
